- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: UpdateRaw
      shell: apt-get update -y

    - name: UpdateRaw
      shell: apt-get upgrade -y

    - name: Pull hello-world image
      docker_image:
        name: hello-world
        state: present

    - name: create folder
      shell: mkdir /var/log/test