version: '3.8'

volumes:
  semaphore-postgres: 

networks:
  semaphore-net:

services:
  postgres:
    image: postgres:14
    hostname: postgres
    ports:
      - 5433:5432
    deploy:
      placement:
        constraints: 
          - node.hostname == node01
    networks:
      semaphore-net:
    volumes: 
      - semaphore-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=semaphore
      - POSTGRES_PASSWORD=semaphore
      - POSTGRES_DB=semaphore

  semaphore:
    image: semaphoreui/semaphore:latest
    hostname: semaphore
    ports:
      - 3000:3000
    volumes:
      - /home/node01/ansible_vault:/tmp/semaphore/ansible_vault
    networks:
      semaphore-net:
    deploy:
      placement:
        constraints: 
          - node.hostname == node01
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=semaphore
      - SEMAPHORE_DB_HOST=postgres 
      - SEMAPHORE_DB_PORT=5432 
      - SEMAPHORE_DB_DIALECT=postgres 
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=changeme
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      - SEMAPHORE_LDAP_ACTIVATED='no'
      - TZ=UTC

