- hosts: primary_node
  become: yes
  tasks:
    - name: Set the locale
      ansible.posix.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Update all host/vm packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        name: "*"
        state: latest