- name: Example Playbook
  hosts: all
  vars_files:
    - "~/ansible_vault/secrets.yaml"
  tasks:
    - name: Print secret variables
      debug:
        msg: "Node 01 Key: {{ node01key }}, Node 02 Key: {{ node02key }}, Node 03 Key: {{ node03key }}"