- hosts: primary_node
  become: yes
  gather_facts: yes
  tasks:
    - name: Gather facts
      ansible.builtin.setup
      
    - name: Set the locale
      ansible.builtin.command: update-locale LANG=en_US.UTF-8

    - name: Update all host/vm packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        name: "*"
        state: latest
